#!/bin/bash

source /etc/jailbox/config
USAGE="Run command without tor.\nUsage: $(basename $0) [-hv] [-u user] [-c command]"
USER="${current_user}"
CMD="bash"

# parse command line arguments
while getopts "hvu:c:" opt; do
  case "${opt}" in
  h )
    echo -e $USAGE
    exit 0
    ;;
  v )
    echo "Jailbox version ${version}"
    exit 0
    ;;
  u )
    USER="$OPTARG"
    ;;
  c )
    CMD="$OPTARG"
    ;;
  esac
done
shift $(expr $OPTIND - 1)

if [ $UID -ne 0 ]; then
  echo "Superuser rights required" >&2
  exit 2
fi

# run command in isolated namespace
ip netns exec "${namespace}" su -c "${CMD}" "${USER}"
